source "https://supermarket.getchef.com"

cookbook "apt"
cookbook "build-essential"
cookbook "git"
cookbook "nginx", github: "patcon/nginx", branch: "281-poodle-vuln"
cookbook "openssl"
cookbook "postgresql"
cookbook "rbenv"
cookbook "ruby_build"
cookbook "sudo"
